version: '3.1'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: [ 'start-dev' ]
    container_name: keycloak-flowcraft
    ports:
      - "8085:8080"
    volumes:
      - .local/keycloak/:/opt/jboss/keycloak/standalone/data/
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME_URL=http://localhost:8085

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
